name: SonarQube Scan

on:
  workflow_call:
    inputs:
      projectKey:
        required: true
        type: string
      organization:
        required: true
        type: string

jobs:
  sonar-scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Run SonarQube Scan
        uses: sonarsource/sonarcloud-github-action@v2
        with:
          args: >
            -Dsonar.projectKey=${{ inputs.projectKey }}
            -Dsonar.organization=${{ inputs.organization }}
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
