name: Centralized CI/CD Dispatcher

on:
  workflow_call:
    inputs:
      tech_stack:
        description: "Technology stack (java/python/node)"
        required: true
        type: string
      sonar_enabled:
        description: "Enable SonarQube scan (true/false)"
        required: false
        default: "false"
        type: string
      sonar_projectKey:
        description: "SonarQube Project Key"
        required: false
        type: string
      sonar_org:
        description: "SonarQube Organization"
        required: false
        type: string

jobs:
  validate-input:
    runs-on: ubuntu-latest
    outputs:
      stack: ${{ steps.set-stack.outputs.stack }}
    steps:
      - name: Validate tech stack input
        id: set-stack
        run: |
          SUPPORTED="java python node"
          INPUT="${{ github.event.inputs.tech_stack }}"

          if echo "$SUPPORTED" | grep -wq "$INPUT"; then
            echo "✅ Valid stack: $INPUT"
            echo "stack=$INPUT" >> $GITHUB_OUTPUT
          else
            echo "❌ Invalid tech stack: $INPUT"
            echo "Available options: $SUPPORTED"
            exit 1

  java:
    needs: validate-input
    if: ${{ needs.validate-input.outputs.stack == 'java' }}
    uses: ./.github/actions/java.yml
    secrets: inherit

  python:
    needs: validate-input
    if: ${{ needs.validate-input.outputs.stack == 'python' }}
    uses: ./.github/actions/python.yml
    secrets: inherit

  node:
    needs: validate-input
    if: ${{ needs.validate-input.outputs.stack == 'node' }}
    uses: ./.github/actions/node.yml
    secrets: inherit

  sonar:
    needs: [java, python, node]
    if: ${{ github.event.inputs.sonar_enabled == 'true' }}
    uses: ./.github/actions/sonarqube.yml
    with:
      projectKey: ${{ github.event.inputs.sonar_projectKey }}
      organization: ${{ github.event.inputs.sonar_org }}
    secrets: inherit
