name: Node CI

on:
  push:
    branches: [ main, develop ]
    paths:
      - 'node-app/**'
      - '.github/workflows/node-ci.yml'
  pull_request:
    branches: [ main, develop ]
    paths:
      - 'node-app/**'
      - '.github/workflows/node-ci.yml'
  workflow_dispatch: {}

permissions:
  contents: read

concurrency:
  group: node-ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-test:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: node-app

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # --- Setup Node.js with caching IF a lockfile exists ---
      - name: Setup Node.js (cached)
        if: ${{ hashFiles('node-app/**/package-lock.json', 'node-app/**/pnpm-lock.yaml', 'node-app/**/yarn.lock') != '' }}
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: npm
          cache-dep
